site_name: My Docs
site_url: https://example.com
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
  #dark mode:
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: dark mode
    primary: blue

  #light mode:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off
      name: light mode
    primary: blue

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  generator: false
  social:
    - icon: simple/youtube
      link: https://youtube.com/@urbanesha
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/urbanesha/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/urbanesha

copyright: Copyright &copy; 2025 Urbanesha