site_name: Urbanesha Tutorials
site_url: https://example.com
#repo_url: https://github.com/RivanAji/gravigis
theme:
  name: material
  features:
    - navigation.tabs
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
  #dark mode:
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: dark mode
    primary: blue
  #light mode:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off
      name: light mode
    primary: blue

nav:
    - Home: 
      - Welcome: index.md
      - Report Issues: https://github.com/RivanAji/gravigis/issues
    - LanduseSim:
      - Getting Started: landusesim/landusesim.md
      - Install: landusesim/ls_install.md
      - Tutorial: landusesim/ls_tutorial.md
      - FAQ: landusesim/ls_faq.md
      - Changelog: landusesim/ls_changelog.md
      - Examples:
        - landusesim/ls_example1.md
    - GraviGIS:
      - Getting Started: gravigis/gravigis.md
      - Install: gravigis/gr_install.md
      - Tutorial: gravigis/gr_tutorial.md
      - FAQ: gravigis/gr_faq.md
      - Changelog: gravigis/gr_changelog.md
      - Examples:
        - gravigis/gr_example1.md
    - UrbanSCAD:
      - Getting Started: urbanscad/urbanscad.md
      - Install: urbanscad/us_install.md
      - Tutorial: urbanscad/us_tutorial.md
      - FAQ: urbanscad/us_faq.md
      - Changelog: urbanscad/us_changelog.md
      - Examples:
        - urbanscad/us_example1.md
    - UrbanRVM:
      - Getting Started: urbanrvm/urbanrvm.md
      - Install: urbanrvm/ur_install.md
      - Tutorial: urbanrvm/ur_tutorial.md
      - FAQ: urbanrvm/ur_faq.md
      - Changelog: urbanrvm/ur_changelog.md
      - Examples:
        - urbanrvm/ur_example1.md
    - Tranetsim:
      - Getting Started: tranetsim/tranetsim.md
      - Install: tranetsim/ts_install.md
      - Tutorial: tranetsim/ts_tutorial.md
      - FAQ: tranetsim/ts_faq.md
      - Changelog: tranetsim/ts_changelog.md
      - Examples:
        - tranetsim/ts_example1.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  generator: false
  social:
    - icon: simple/youtube
      link: https://youtube.com/@urbanesha
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/urbanesha/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/urbanesha
extra_css:
  - styles/extra.css

copyright: Copyright &copy; 2025 Urbanesha